/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 greek-model.glb --transform 
Files: greek-model.glb [9.34MB] > C:\Users\Morad\react-main-projects\react-portfolio-2024\public\models\greek-model-transformed.glb [649.92KB] (93%)
Author: SomeDude (https://sketchfab.com/Patyot.Suttipreecha)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/zeus-idle-ed4308bda4604effb798d107c910ce37
Title: Zeus Idle
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function GreekModel(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('./models/greek-model-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes._rootJoint} />
        <skinnedMesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.BodyMat} skeleton={nodes.Object_18.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
        <skinnedMesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.HairMat} skeleton={nodes.Object_20.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
        <skinnedMesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials.HairMat} skeleton={nodes.Object_22.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
        <skinnedMesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials.HairMat} skeleton={nodes.Object_24.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
        <skinnedMesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials.AccessorieMat} skeleton={nodes.Object_26.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
        <skinnedMesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials.AccessorieMat} skeleton={nodes.Object_28.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
        <skinnedMesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials.BodyMat} skeleton={nodes.Object_30.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
        <skinnedMesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials.AccessorieMat} skeleton={nodes.Object_32.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
        <skinnedMesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials.BodyMat} skeleton={nodes.Object_34.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/greek-model-transformed.glb')
