/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 spaceman.glb --transform 
Files: spaceman.glb [5.09MB] > C:\Users\Morad\react-main-projects\react-portfolio-2024\public\models\spaceman-transformed.glb [717.98KB] (86%)
Author: jimena.20 (https://sketchfab.com/jimenaalvarado2000)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/person-projet-effects-ad08aceebc73490b9dd9fdd9d9777700
Title: Person Projet Effects
*/

import React, {useLayoutEffect, useRef} from 'react'
import { useFrame, useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations, useScroll } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Spaceman(props) {
  const { scene, animations } = useGLTF('./models/spaceman-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const spacemanRef = useRef()
  const scroll = useScroll()

  // useFrame(({clock}) => {
  //   spacemanRef.current.rotation.y = clock.getElapsedTime() * .5
  // })

  // useLayoutEffect()=> {
  //   tl.current = 
  // }

  return (
    <group {...props} dispose={null} ref={spacemanRef} className="spaceman">
      <group name="Sketchfab_Scene">
        <mesh material={materials.Metal}>
          <primitive object={nodes.GLTF_created_0_rootJoint} />
        <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials['Material.001']} skeleton={nodes.Object_7.skeleton} position={[0, -1.084, 0]} rotation={[0, Math.PI / 2, 0]} />
        <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.material_0}  skeleton={nodes.Object_9.skeleton} position={[0, -1.084, 0]} rotation={[0, Math.PI / 2, 0]} />
        <skinnedMesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials['Material.001']} skeleton={nodes.Object_11.skeleton} position={[0, -1.084, 0]} rotation={[0, Math.PI / 2, 0]} />
        <skinnedMesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials['Material.001']} skeleton={nodes.Object_13.skeleton} position={[0, -1.084, 0]} rotation={[0, Math.PI / 2, 0]} />
        <skinnedMesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials['Material.001']} skeleton={nodes.Object_15.skeleton} position={[0, -1.084, 0]} rotation={[0, Math.PI / 2, 0]} />
        <skinnedMesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials['Material.001']} skeleton={nodes.Object_17.skeleton} position={[0, -1.084, 0]} rotation={[0, Math.PI / 2, 0]} />
        <skinnedMesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials['Material.001']} skeleton={nodes.Object_19.skeleton} position={[0, -1.084, 0]} rotation={[0, Math.PI / 2, 0]} />
        <skinnedMesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials['Material.002']} skeleton={nodes.Object_21.skeleton} position={[0, -1.084, 0]} rotation={[0, Math.PI / 2, 0]} />
        <skinnedMesh name="Object_23" geometry={nodes.Object_23.geometry} material={materials.material_0} skeleton={nodes.Object_23.skeleton} position={[0, -1.084, 0]} rotation={[0, Math.PI / 2, 0]} />
        <skinnedMesh name="Object_25" geometry={nodes.Object_25.geometry} material={materials.material_0} skeleton={nodes.Object_25.skeleton} position={[0, -1.084, 0]} rotation={[0, Math.PI / 2, 0]} />
        <skinnedMesh name="Object_27" geometry={nodes.Object_27.geometry} material={materials.Material} skeleton={nodes.Object_27.skeleton} position={[0, -1.084, 0]} rotation={[0, Math.PI / 2, 0]} />
      </mesh>
      </group>
        
        
    </group>
  )
}

useGLTF.preload('./models/spaceman-transformed.glb')
